### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by F36** [1337w0rm/YeetMeet#7] opened 2020-09-25 08:26 UTC
https://telegra.ph/file/476303a58c66f6ec193d8.jpg

check this image

**Comment by mehta-seth** [comment] 2020-09-25 21:46
![photo_2020-09-26_03-12-35](https://user-images.githubusercontent.com/69599730/94318434-32ca6380-ffa6-11ea-854a-3bb840113d82.jpg)


Could you please check this

**Comment by 1337w0rm** [comment] 2020-09-26 13:05
I've successfully reproduced the issue. Will try to fix it in a couple of days.

**Comment by 1337w0rm** [comment] 2020-09-26 14:39
Pushed Fix. Test it out and let me know.

**Comment by F36** [comment] 2020-09-26 15:15
OK TESTING

**Comment by F36** [comment] 2020-09-26 15:27
@1337w0rm google is smart it send captcha now 

https://telegra.ph/file/41fca2b08386b1683c451.jpg

**Comment by F36** [comment] 2020-09-26 15:33
now zoom is giving captcha https://telegra.ph/file/0bc447b9bd38b298b099d.jpg

**Comment by 1337w0rm** [comment] 2020-09-26 15:37
It is because you've logged in a lot of time. Use some other google account. And more thing keep the login process running until you receive a "Logged In" message on Telegram.

**Comment by mehta-seth** [comment] 2020-09-26 15:39
![photo_2020-09-26_20-26-48](https://user-images.githubusercontent.com/69599730/94343668-44a81700-0037-11eb-9ff7-073ac6e3037b.jpg)


![photo_2020-09-26_21-06-00](https://user-images.githubusercontent.com/69599730/94344359-5b9d3800-003c-11eb-9a1f-b2082d1a15b9.jpg)


**Thank You for the fix. This time it successfully logged in Google browser but is stuck at Name and Captcha. 
Also got a mail from Google: Someone has your password XD (maybe because I tried multiple times)**

**Comment by F36** [comment] 2020-09-26 15:43
> It is because you've logged in a lot of time. Use some other google account. And more thing keep the login process running until you receive a "Logged In" message on Telegram.

yup logged in but zoom captcha

**Comment by 1337w0rm** [comment] 2020-09-26 16:13
> ![photo_2020-09-26_20-26-48](https://user-images.githubusercontent.com/69599730/94343668-44a81700-0037-11eb-9ff7-073ac6e3037b.jpg)
> 
> ![photo_2020-09-26_21-06-00](https://user-images.githubusercontent.com/69599730/94344359-5b9d3800-003c-11eb-9a1f-b2082d1a15b9.jpg)
> 
> **Thank You for the fix. This time it successfully logged in Google browser but is stuck at Name and Captcha. Also got a mail from Google: Someone has your password XD (maybe because I tried multiple times)**

I'm not getting any captcha on Zoom. In the screenshot it looks like your account isn't logged in on Zoom and that's why you're getting a captcha . Try deleting the `zoom.pkl` file from you directory and re-login again.

**Comment by mehta-seth** [comment] 2020-09-27 06:47
So I deployed the bot again.
Noticed few things:
I tried changing the email address as you said. It is again stuck at the Name and Captcha. I made sure that email address is logged in Zoom. I can attach a screenshot but its the same as above.

Also when I tried deploying on my local machine, it takes the name of my computer as the Username for Google Login which is weird and causes error. 

When you are referring to login to your google account on the local machine, do you mean on the chromedriver initiated tab or normal browser? As login there (chromedriver tab) is unsuccessful (Error: This browser or app may not be secure. 
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.)

Also, do you have a support group for this on Telegram?

**Comment by 1337w0rm** [comment] 2020-09-27 07:10
> So I deployed the bot again.
> Noticed few things:
> I tried changing the email address as you said. It is again stuck at the Name and Captcha. I made sure that email address is logged in Zoom. I can attach a screenshot but its the same as above.
> 
> Also when I tried deploying on my local machine, it takes the name of my computer as the Username for Google Login which is weird and causes error.
> 
> When you are referring to login to your google account on the local machine, do you mean on the chromedriver initiated tab or normal browser? As login there (chromedriver tab) is unsuccessful (Error: This browser or app may not be secure.
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.)
> 
> Also, do you have a support group for this on Telegram?

1. Are you using the updated repository ? I pushed an update last night.

2. If you're using the latest repo did you  first deleted the zoom.pkl file in your repo directory before trying to relogin ? The zoom.pkl file store the cookies which helps you to login next time without providing credentials.

3. By re logging in I mean in the chromedriver initiated tab and for the browser or app may not be secure error is the latest fix not working ?

4. Currently I don't have a support group but you can text me on Telegram @adityaxingh

**Closed as completed** 2020-09-29 05:18 UTC
